Added some updates to website
adonisjs/legacy-documentation pull request #8
Opened 2016-12-15 08:26 UTC by keeross

So, I made several updates to website, the bar with search is now fixed. At the same time had to replace Hellobar with a native one, because it has a more predictable behavior (Hellobar changed its position depending on console being opened or not). Now it looks like this: 

![alt text](https://d3vv6lp55qjaqc.cloudfront.net/items/0y2f1Q472s0P2W10450k/Screen%20Recording%202016-12-15%20at%2002.34%20AM.gif?X-CloudApp-Visitor-Id=2661335&v=348d8b46)

2016-12-15 09:14 UTC, RomainLanz requested changes

2016-12-15 09:14 UTC, RomainLanz commented on ace
> +kernel()
This file shouldn't be changed, also there's no new line at the end of the file.

2016-12-15 09:15 UTC, RomainLanz commented
Also you may remove all `bower_components` files that is not needed.

Note that you need to add a new line at the end of every files (it isn't the case).

You should installe `editorconfig` plugin in your IDE/TextEditor to configure automatically these thing (https://github.com/adonisjs/adonis-documentation/blob/develop/.editorconfig).

2016-12-15 09:55 UTC, thetutlage commented
Also you can please make the bar match the hello bar background color. Which is basically the theme purple color?

2016-12-15 10:43 UTC, keeross commented
Made all the fixes and changed the color of the topbar, now it will look like this:

![img](https://d3vv6lp55qjaqc.cloudfront.net/items/2b391E3Q401I06381R0S/Screen%20Recording%202016-12-15%20at%2012.41%20PM.gif?X-CloudApp-Visitor-Id=2661335&v=636ad72c)

2016-12-15 11:00 UTC, RomainLanz commented
Cool, could you squash to one commit?

2016-12-15 11:55 UTC, keeross commented
Hm, I think I rebased it, but it didn't show up here https://github.com/keeross/adonis-documentation/commit/d3f4b60200b3e770e3c95dfab4584233148f4dee
I did something wrong?

2016-12-15 12:13 UTC, keeross commented
Okay, done, git bugged a bit

2016-12-16 09:15 UTC, merged

2016-12-16 09:15 UTC, thetutlage commented
Thanks @keeross 😄